{#- OZI 0.1
# ozi/templates/black.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.black]
extend-exclude = "(\\.pyi|{{ spec.python.lint.exclude|join('|') }}",
line-length = {{ spec.python.src.format.max_line_length }}