{#- OZI 0.1
# ozi/templates/doc8.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.doc8]
ignore = ["D000", "D002"]