{#- OZI 0.1
# ozi/templates/flake8.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.flake8]
ban-relative-imports = "parents"
max-line-length = {{ spec.python.src.format.max_line_length }}
extend-exclude  = [
{%- for exclude in spec.python.lint.exclude %}
    "{{ exclude }}",
{%- endfor %}
    "build-env-*",
    "build*",
    "*.pyi"
]
extend-ignore   = "E203,E501"
extend-select   = "B950"