{#- OZI 0.1
# ozi/templates/semantic_release.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.setuptools_scm]
write_to_template = """{% include 'project.PKG-INFO' %}"""
fallback_version = "@VCS_TAG@"
parentdir_prefix_version = "{{ project.name }}-"
tag_regex = "^(?P<prefix>v)?(?P<version>[^\\+]+)(?P<suffix>.*)?$"